# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: spedn
version: '0.3.0'
git: "https://bitbucket.org/o-studio/spedn.git"
license: MIT
author: (o) Software
maintainer: (o) Software
synopsis: Bitcoin Cash smart contracts compiler.
description: Spedn is a high-level, strongly typed smart contract language compiled to Bitcoin Script.
category: Bitcoin

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - megaparsec
  - parser-combinators
  - mtl
  - containers
  - time
  - persist
  - bytestring
  source-dirs: library

executables:
  spedn:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - spedn
    - bytestring
    - base16-bytestring
    - optparse-applicative
    - containers
    - deepseq
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints

benchmarks:
  spedn-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - spedn
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  spedn-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - spedn
    - mtl
    - containers
    - time
    - megaparsec
    - tasty
    - tasty-hspec
    - hspec
    - QuickCheck
    - quickcheck-instances
    - QuickCheck-GenT
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -fno-warn-orphans
